version: "3"
services:
  ui:
    build: ./docker/ui
    volumes:
      - ./ui:/var/www/html/
    working_dir: /var/www/html/ui
    command: yarn start
    ports:
      - "3000:3000"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: go
      MYSQL_PASSWORD: gurupen
      MYSQL_DATABASE: gurupen
      MYSQL_USER: gurupen
      MYSQL_PASSWORD: gurupen
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    image: alpine:3.7
    #build: ./docker/api
    volumes:
      - ./api:/go/src/gurupen_api
    ports: 
  nginx:
    build: ./docker/nginx
    ports:
      - "1234:1234"