version: "3"
services:
  ui:
    build: ./ui
    volumes:
      - ./ui:/var/www/html/
    working_dir: /var/www/html/ui
    command: yarn start
    ports:
      - "3000:3000"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: go
      MYSQL_PASSWORD: gurupen
      MYSQL_DATABASE: gurupen
      MYSQL_USER: gurupen
      MYSQL_PASSWORD: gurupen
      DB_PING_USER: gurupen
      DB_PING_USER_PASSWORD: gurupen
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    image: alpine:3.7
    volumes:
      - ./api:/go/src/api
    depends_on:
      - db
    working_dir: /go/src/api/bin
    entrypoint: "/bin/sh -c 'chmod 777 ./start.sh && ./start.sh'"
    ports:
      - "1323:1323"
  nginx:
    build: ./docker/nginx
    ports:
      - "1234:1234"